### ISSUE TITLE
AirtonAC problème d'installation

### ISSUE THREAD

**Issue by VBill45** [gpajot/airton-ac#15]
Bonjour, j'ai essayé d'installer votre plugin domoticz mais j'ai une erreur sur la deuxième commande:
python3 -m airton_ac.domoticz.install

me renvoi  : 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.9/site-packages/airton_ac/domoticz/install.py", line 9, in <module>
    target.parent.mkdir()
  File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/domoticz/domoticz/plugins/AirtonAC'

Le prog python veut aller apparement à /home/domoticz/domoticz... au lieu de /home/pi/domoticz

**Comment by VBill45** [comment]
J'ai modifié le fichier : 
/home/pi/.local/lib/python3.9/site-packages/airton_ac/domoticz/install.py

ligne 5
    domoticz_path = sys.argv[1] if len(sys.argv) > 1 else "/home/domoticz/domoticz"
par
    domoticz_path = sys.argv[1] if len(sys.argv) > 1 else "/home/pi/domoticz"

L'install c'est faite sans erreur et le plugin fonctionne

**Comment by gpajot** [comment]
Bonjour,
Effectivement il faudrait que je le mentionne sur la doc, il est possible de passer un chemin en paramètre de la commande, dans votre cas:
`python3 -m airton_ac.domoticz.install "/home/pi/domoticz"`
Hésitez pas a me remonter des problèmes que vous pouvez rencontrer a l'utilisation 😉
